# Generated by Django 2.2 on 2021-06-16 14:37

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        users.models.Students.StudentNumber.Operation(),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('uuid', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^student-\\d{12}')])),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_pw', models.TextField()),
                ('student_number', users.models.Students.StudentNumber.Field())
            ],
        ),
    ]
